{
 "title": "Covid Cases over Time",
 "time": { "from": "now-1y/y", "to": "now" },
 "panels": [
  {
   "title": "Active Cases over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  active as \"Active Cases\"\nFROM covidcases\nWHERE\n  $__timeFilter(date)"
    }
   ]
  },
  {
   "title": "Confirmed Cases over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  confirmed as \"Confirmed Cases\"\nFROM covidcases\nWHERE\n  $__timeFilter(date)"
    }
   ]
  },
  {
   "title": "Recovered Cases over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  recovered as \"Recovered Cases\"\nFROM covidcases\nWHERE\n  $__timeFilter(date)"
    }
   ]
  },
  {
   "title": "Death Cases over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  deaths as \"Death Cases\"\nFROM covidcases\nWHERE\n  $__timeFilter(date)"
    }
   ]
  }
 ]
}